import "@/styles/globals.css";

import "@mantine/core/styles.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { CrediterAppShell } from "@/_components/app-shell";
import { MantineProvider } from "@mantine/core";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <TRPCReactProvider>
            <CrediterAppShell>{children}</CrediterAppShell>
          </TRPCReactProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
